spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    ddl-auto: none