export const TODO = {
  ADD: "ADD_TODO",
  UPDATE: "UPDATE_TODO",
  DELETE: "DELETE_TODO"
}

export const LOGIN = {
  PENDING: "LOGIN_PENDING",
  SUCCESS: "LOGIN_SUCCESS",
  ERROR: "LOGIN_ERROR"
}

export const LOGOUT = {
  SUCCESS: "LOGOUT_SUCCESS"
}

export const SESSION = {
  INCREASE_SESSION: "INCREASE_SESSION",
  SESSION_EXPIRED: "SESSION_EXPIRED"
}

export const USER = {
  GET_INFO_PENDING: "GET_USER_INFO_PENDING",
  GET_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
  GET_INFO_ERROR: "GET_USER_INFO_ERROR"
}

export const NOTIFICATION = {
  SESSION_EXPIRED: "SESSION_EXPIRED",
  INVALID_USER: "INVALID_USER",
  CLOSE: "NOTIFICATION_CLOSE",
}
